[package]
name = "mutica-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
mutica = "0.1.0"
tower-lsp = "0.20.0"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
anyhow = "1.0"
